### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by dxp10** [piyushyadav1617/My-Javascript-learnings#1]
Hi friend, could you rate my repositories and I'll rate yours at the same time? Thanks!

**Comment by piyushyadav1617** [comment]
yeah sure

**Comment by piyushyadav1617** [comment]
@dxp10 what do you mean by rate? Do you mean star them?

**Comment by dxp10** [comment]
Yes

**Comment by piyushyadav1617** [comment]
I suggest you delete these comments afterwards.
